name: "Veros Advisors"
markdown: redcarpet
pygments: true

# url: "http://verosadvisors.com" # for production
url: "http://0.0.0.0:4000" # for staging

exclude: ["CNAME", "README.md", "less"] # exclude files from site build

paginate: 10 # maximum number of posts youâ€™d like to be displayed per page
paginate_path: "blog/page:num" # specify where the destination of the pagination pages